In [3]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

le = preprocessing.LabelEncoder()

In [4]:
input_df = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')
input_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [5]:
clean_df=input_df.drop(['FCVC','NCP','CH2O','FAF','TUE'],axis=1)
clean_df['family_history_with_overweight'].unique()
clean_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,Sometimes,no,no,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,Sometimes,yes,yes,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,Sometimes,no,no,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,Sometimes,no,no,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,Sometimes,no,no,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III

In [45]:
df = clean_df[['Gender','family_history_with_overweight','FAVC','CAEC','SMOKE',
         'SCC','CALC','MTRANS','NObeyesdad']]

df_columns = df.columns
for i in df_columns:
    le = preprocessing.LabelEncoder()
    le.fit(df[i])
    df[i] = le.transform(df[i])

/var/folders/5h/cd0pm76j0_5bp1m0y02pf9c40000gn/T/ipykernel_73664/528198924.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i] = le.transform(df[i])

In [46]:
df

,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,0,1,0,2,0,0,3,3,1
1,0,1,0,2,1,1,2,3,1
2,1,1,0,2,0,0,1,3,1
3,1,0,0,2,0,0,1,4,5
4,1,0,0,2,0,0,2,3,6
...,...,...,...,...,...,...,...,...,...
2106,0,1,1,2,0,0,2,3,4
2107,0,1,1,2,0,0,2,3,4
2108,0,1,1,2,0,0,2,3,4
2109,0,1,1,2,0,0,2,3,4
2110,0,1,1,2,0,0,2,3,4

In [47]:
df[['Height','Weight']]=clean_df[['Height','Weight']].round(2)
df['Age']=clean_df['Age'].astype(int)

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [48]:
scaler = preprocessing.MinMaxScaler()

df[['Height','Weight','Age']] = scaler.fit_transform(df[['Height','Weight','Age']])

In [49]:
df

,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad,Height,Weight,Age
0,0,1,0,2,0,0,3,3,1,0.320755,0.186567,0.148936
1,0,1,0,2,1,1,2,3,1,0.132075,0.126866,0.148936
2,1,1,0,2,0,0,1,3,1,0.660377,0.283582,0.191489
3,1,0,0,2,0,0,1,4,5,0.660377,0.358209,0.276596
4,1,0,0,2,0,0,2,3,6,0.622642,0.379104,0.170213
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,0,1,1,2,0,0,2,3,4,0.490566,0.689627,0.127660
2107,0,1,1,2,0,0,2,3,4,0.566038,0.707015,0.148936
2108,0,1,1,2,0,0,2,3,4,0.566038,0.706642,0.170213
2109,0,1,1,2,0,0,2,3,4,0.547170,0.704104,0.212766
2110,0,1,1,2,0,0,2,3,4,0.547170,0.705000,0.191489

In [50]:
from sklearn.model_selection import train_test_split

X=df.drop(['NObeyesdad'], axis=1)
y=df['NObeyesdad']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [51]:
regr = RandomForestClassifier(max_depth=10, random_state=42)

In [52]:
regr.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [53]:
y_pred_test = regr.predict(X_test)

In [54]:
accuracy_score(y_test, y_pred_test)

0.9511041009463722

In [55]:
filename = 'finalized_model.sav'
filename_le = 'label_encoder.sav'
filename_minmax = 'min_max_scalar.sav'

pickle.dump(regr, open(filename, 'wb'))
pickle.dump(le, open(filename_le, 'wb'))
pickle.dump(scaler, open(filename_minmax, 'wb'))


# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.9511041009463722

In [56]:
# filename_le = 'label_encoder.sav'

# pickle.dump(le, open(filename_le, 'wb'))

In [57]:
loaded_model.predict(X_test[:1])

array([6])

In [58]:
X_test[:1]

,Gender,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,Height,Weight,Age
1179,1,1,1,2,0,0,3,0,0.54717,0.341269,0.702128

In [59]:
loaded_model.predict([[1,1,1,2,0,0,2,0,0.340426,0.584906,0.544403]])

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([3])

In [63]:
labelEncoderFile = pickle.load(open(filename_le, 'rb'))
gender = labelEncoderFile.transform(['Female','yes','no','Sometimes','no','no','no','Public_Transportation'])

ValueError: y contains previously unseen labels: 'Female'

In [62]:
gender

array([0, 4, 3, 2, 3, 3, 3, 1])

In [ ]:
MinMaxScalerFile = pickle.load(open(filename_minmax, 'rb'))
height=1.62
weight = 64
age = 21
test = MinMaxScalerFile.transform([[1.62,64,21]])

In [ ]:
test[0]

In [ ]:
test[0][1]